### ISSUE TITLE
Use Oxygen.3a as minimal Target Platform

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1168]
Id like to go on oxygen as minimal supported platform.

any comments cc @svenefftinge @szarnekow @kthoms

**Comment by svenefftinge** [comment]
Is there something specific you want to use? 
I assume this doesn't affect xtext-core, correct?

**Comment by cdietrich** [comment]
it affects everything. we at itemis have very limited resources and you at typefox dont seem to be interested in contrubuting anything that makes xtext work with oxygen, photon, java 9 etc.
and this in a time when platform and java move and change, and we use tons of internal api

so not supporting luna, kepler and mars frees us from the burden of supporting 20 versions.

**Comment by svenefftinge** [comment]
I'm fine with that change, I just don't like to break clients without a real reason. AFAIK, in xtext-core, we only use public API of super mature eclipse projects. So there should be no burden there.

**Comment by cdietrich** [comment]
So would you help to support from Luna to Photon? If you would do I would be fine with as is

**Comment by cdietrich** [comment]
And no we use internal api in core / extras as well

**Comment by cdietrich** [comment]
things to consider: minimal guava version

**Comment by ArneDeutsch** [comment]
I would appreciate the update to a more recent version. Gains I see:
- Less manual testing per release because we need to test against less platforms
- Possibility to use API introduced in the last few years from projects we depend on

On the other hand the risks seem quite minor. A customer that is still on Luna will most probably not update Xtext alone to version 2.15. Why should he update to most recent Xtext but stay with other projects at very dated version? And in my opinion, to be honest, if someone absolutly want to stay with dated eclipse it should be ok for him to stay with dated Xtext as well.

From this viewpoint an updated target platform is not a breakage of any clients. It is just normal to cut old threads to be able to move ahead.

**Comment by kthoms** [comment]
I'm a bit undecided what minimal version we should use, either Oxygen or Photon. If we would use Photon at least, we could assume that the target platform for the build has already code mining for example. At the moment, the build uses a Photon target building org.eclipse.xtext.ui.codemining even when older platforms are used for the rest of the build.

I tend a bit for Photon as base now. This does not mean that a newer Xtext version >2.14 can't be installed on an older platform, it is just that we won't guarantee it is being supported by the Xtext project team.

**Comment by cdietrich** [comment]
i am not so briskly in that regard. my main paintpoint is that it still is unclear how the new release cycle of platform and jdt will work out and how we have to adopt for that. thus i am not sure if to cut to the "latest greatest" is a good idea. @szarnekow  @holgerschill what do you think

**Comment by cdietrich** [comment]
p.s.: with oxygen i mean sr 3a

**Comment by kthoms** [comment]
It is a bit harder to communicate that we only support Oxygen.3a at least but not Oxygen in general.

**Comment by JanKoehnlein** [comment]
I often had customers stick to a specific version of Eclipse because of other (commercial or OS) plug-ins in their workbench that cannot be migrated easily. After all, Eclipse is not just the projects from the release train, but a platform to integrate all kind of things.

Anyway, if it's too much effort to keep backwards compatibility, we should lift up the TP. I'd prefer Neon or Oxygen. Just supporting the latest version for one single UI feature feels a bit too harsh.

**Comment by kthoms** [comment]
We also have these customers, and they typically are also using older Xtext versions. It is also not that newer Xtext versions won't work on older platforms, likely they'll do. It is just not guaranteed anymore by the core project. For the unlikely case that there are issues, they are still customers that can get help.
With the next version of Xtext, Photon is already superseeded by Eclipse 4.9. Future platform versions are coming now in 3 months cycles. So setting now Photon as target might not be too limited with respect to the very near future.

**Comment by dhuebner** [comment]
Keeping an Xtext branch for maintenance and bugfixing in current state shouldn't be a problem, right?
I mean, the customers do not need a fancy new features, like in example code mining, but need a possibility to fix critical bugs. AFAIK building and deploying works well now so I hope one can produce a 2.14.x release at any time, right?

However, I also prefer Neon as a minimal eclipse platform version.

**Comment by cdietrich** [comment]
we decided to go with Oxygen 3a as minimal platform

**Comment by kthoms** [comment]
I think we finally can check in those classes generated by Xtend which make use of generic types in the platform, e.g. of IAdaptable. There are sources in xtext-eclipse and xtext-xtend affected by this.

**Comment by cdietrich** [comment]
See my open prs

**Comment by kthoms** [comment]
ah, ok

**Comment by cdietrich** [comment]
Pushed fix for warnings.@kthoms are you gonna push a fix to inc. the required version

**Comment by cdietrich** [comment]
TODO for 2.16: increase version constraints for platform and jdt in manifests

**Comment by kthoms** [comment]
I think this is done now.
