### ISSUE TITLE
Wrongly pulling dependency to "2.17.0-SNAPSHOT" for Xtext 2.16.0

### ISSUE THREAD

**Issue by michael-schnell** [eclipse/xtext#1379]
As of yesterday a build that previously worked fine started failing because dependency "org.eclipse.xtend:org.eclipse.xtend.lib:jar:2.17.0-SNAPSHOT" was not avialable:
https://jenkins.fuin.org/job/ddd-templates/35/console

```
Could not resolve dependencies for project org.fuin.dsl.ddd:ddd-templates:jar:0.2.0-SNAPSHOT: 
Failed to collect dependencies at org.eclipse.xtext:org.eclipse.xtext.testing:jar:2.16.0 -> org.eclipse.xtext:org.eclipse.xtext.ide:jar:2.16.0 -> org.eclipse.lsp4j:org.eclipse.lsp4j:jar:0.6.0 -> org.eclipse.lsp4j:org.eclipse.lsp4j.generator:jar:0.6.0 -> org.eclipse.xtend:org.eclipse.xtend.lib:jar:2.17.0-SNAPSHOT: Failed to read artifact descriptor for org.eclipse.xtend:org.eclipse.xtend.lib:jar:2.17.0-SNAPSHOT: Could not transfer artifact org.eclipse.xtext:xtext-dev-bom:pom:2.17.0-SNAPSHOT

```
It only uses the release version of Xtext/Xtend (2.16.0) and no snapshots. 

**Dependency chain**
```
org.eclipse.xtext:org.eclipse.xtext.testing:jar:2.16.0 -> 
org.eclipse.xtext:org.eclipse.xtext.ide:jar:2.16.0 -> 
org.eclipse.lsp4j:org.eclipse.lsp4j:jar:0.6.0 -> 
org.eclipse.lsp4j:org.eclipse.lsp4j.generator:jar:0.6.0 -> USES [2.11.0,3) for xtend.lib
org.eclipse.xtend:org.eclipse.xtend.lib:jar:2.17.0-SNAPSHOT
```
**Conclusion**
- lsp4j has an open dependency "[2.11.0,3)" for "org.eclipse.xtend.lib"
- [ddd-templates](https://github.com/fuinorg/ddd-templates) uses some snapshot libraries from [oss.sonatype.org](https://oss.sonatype.org)
- 2.17.0-SNAPSHOTs started to be available at [oss.sonatype.org](https://oss.sonatype.org) on 2019-01-11
- When the build of [ddd-templates](https://github.com/fuinorg/ddd-templates) was started on 2019-01-12 Maven loaded the newer 2.17.0-SNAPSHOT because it was available by [oss.sonatype.org](https://oss.sonatype.org) repo

I'm not sure if this is really an Xtext issue. Maybe lsp4j shouldn't use an open version range.

**Comment by cdietrich** [comment]
I assume the open range leads to all metadata being pulled which then failed cause the deployment of the boom was broken

**Comment by kthoms** [comment]
It seems that you have enabled the snapshot repository on oss.sonatype.org and you should question if you really want to do that. org.eclipse.xtend.lib:jar:2.17.0-SNAPSHOT is only available on the snapshot repository https://oss.sonatype.org/content/repositories/snapshots/ and uses the new BOM xtext-dev-bom:pom:2.17.0-SNAPSHOT, which is also available there now. Actually there was a small issue that the BOM was not available for a short time while xtend.lib snapshot already used that, but this is solved already. So maybe an update problem just, but still questionable to use the snapshot repo. If you want to use the release version check the enabled repositories.

Since your latest build [#36](https://jenkins.fuin.org/job/ddd-templates/) was successful I assume that the issue has gone.

**Comment by michael-schnell** [comment]
Unfortunately it's not that easy. 

I need to use the OSS sonatype snapshot repository as my own snapshots are located there. This means there is no way to just "disable" that repository. 

The main problem is, that there are version ranges in the Maven POM for "org.eclipse.lsp4j:org.eclipse.lsp4j.generator:jar:0.6.0" (it uses a range "[2.11.0,3)" for xtend.lib). That way it will always be possible that a user of the library unexpectedly receives a newer version.

It is really annoying if everything works fine and just running the build leads to an error.

**Comment by kthoms** [comment]
If you declare an explicit dependency before lsp4j (or the dependency that transitively pulls lsp4j), Maven will pick that one.
