### ISSUE TITLE
Remove pollSCM Trigger from Jenkinsfiles

### ISSUE THREAD

**Issue by Hejado** [eclipse/xtext#1494]
Multibranch pipelines are configured to start the branch indexing every two minutes and the (CBI).Jenkinsfile configures a pollSCM trigger to run every 5 minutes. 

We've witnessed this to cause builds to run twice for the same commits. There's a possibility that this is caused by/for parameterized builds only (e.g. Jenkins might not know the specific commit is already being built with the same parameter).

Removing the pollSCM triggers from the Jenkinsfiles should fix this in any case.

**Comment by Hejado** [comment]
Note to future me: Simply removing this trigger will mess up the groovy function for release prepartions where the Jenkinsfiles are parsed to add upstream triggers.

**Comment by kthoms** [comment]
pollSCM are configured only in CBI.Jenkinsfile, except in xtext-umbrella. IIRC this polling was required since we do not have webhooks on JIRO as on JIPP. Only branch indexing did not have the same effect.
I think pollSCM was introduced with reason and we can't remove them.
However, builds should not be issued twice for the same branch, of course.

**Comment by Hejado** [comment]
> Only branch indexing did not have the same effect.

Were the builds not triggered? Because they should be. Maybe it was a bug?

**Comment by cdietrich** [comment]
this really hurts. builds are scheduled always twice which overworks the infrastructure

**Comment by Hejado** [comment]
PRs for removal are approved, but we must remember to adjust release branch preparation also.

**Comment by kthoms** [comment]
Closed via #1510
