### ISSUE TITLE
Add EGit to the Eclipse Xtext development target platform

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#1497]
Currently, after setting up the Xtext development environment and starting an Eclipse Runtime, the EGit plugins are not available:
![screenshot](https://user-images.githubusercontent.com/20393472/60069988-4fc61600-9715-11e9-9efc-24b811441b3d.png)
I suggest to add EGit to the Xtext development target platform (Oomph Setup), e.g. to be able to debug https://github.com/eclipse/xtext-eclipse/issues/1010

**Comment by cdietrich** [comment]
looks like a missing guava to me. can you change which is needed? might be we currently have 27.1 only and our egit needs an older

**Comment by cdietrich** [comment]
i had requested this 1 or 2 year ago and there were voices against this

**Comment by cdietrich** [comment]
@miklossy could you provide a PR?

**Comment by miklossy** [comment]
To be honest I am not exactly aware what to do.

**Comment by miklossy** [comment]
Maybe @hejado together with @kthoms could take care of this.

**Comment by kthoms** [comment]
In order to have EGit on the target platform while not having this in the Oomph Setup, you could make use of Oomph's Modular Target. Go to _Navigate / Open Setup / Workspace_ and add a Modular Target child. Then add a Targlet. In this Targlet add a Repository List with one entry for EGit p2 URL. Also add a requirement for EGit feature.
After running _Help / Peform Setup Tasks_ you should have EGit on your target.

It might be worth to externalize the Targlet as separate file and add it to the Modular Target by URL. Never done that so far, but might be possible. Shall I try to provide such?

**Comment by miklossy** [comment]
Thanks for your quick reply @kthoms. I consider the solution `Modifying the target platform locally ` only as a workaround and I would prefer a general solution so that EGit will be available for all developers out of the box after setting up the Xtext development environment.

It would be awesome if you could try to provide such a general solution. Many thanks in advance!

**Comment by cdietrich** [comment]
fixed
