### ISSUE TITLE
Add AssertableDiagnostics to xtext.testing

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext#1854]
The utilities from xtext.junit4 around AssertableDiagnostics are not available in xtext.testing. Instead, a copy is maintained in xtext.tests.
Check if there is a technical reason why these are not available in xtext.testing and if there is none, move the code from xtext.tests to xtext.testing. Mind the package names. Ensure that they are usable from JUnit4 and Junit5.

**Comment by mundacho** [comment]
Hello, this is my first contribution and I'm a bit lost. I've moved the class AssertableDiagnostics to xtext.testing and committed in my fork. After fixing the compilation errors, everything seems to be OK and tests (for this repo) are passing. (I did .\gradlew.bat test on [eclipse/xtext-core] project)

The ticket says to ensure that they are usable from JUnit4 and Junit5, what can I do to test that? I already have the commit it my fork. Should I create a pull request so that you can check that? Forked repo is at [mundacho/xtext-core]

**Comment by cdietrich** [comment]
we are not really good at junit5 testing.
of course we also would need new junit4/5 tests for it.
you can find some junit 5 tests in the tests folder in the project

**Comment by mundacho** [comment]
well, the AssertableDiagnostics is the same in junit4 too. Just the package is different. Should I also remove it and have the only one in xtext.testing?

**Comment by cdietrich** [comment]
no keep it. i just wanted you to check that the new one is feature par

**Comment by cdietrich** [comment]
@mundacho  can you pr your changes?

**Comment by cdietrich** [comment]
fixed in 2.26
