### ISSUE TITLE
Make old generator more optional

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2042]
Make old generator more optional

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-umbrella/compare/cd_moreOldGeneratorExperiments

**Comment by cdietrich** [comment]
@kthoms @szarnekow what do you think?

**Comment by kthoms** [comment]
I'm understanding that the Xpand dependencies are not part of the Xtext Runtime feature, but from a new feature. This is optional, and Xtext itself is not directly dependent on it. So it looks like a good way forward.

**Comment by szarnekow** [comment]
Good idea! I'm in favor of this proposal.

**Comment by cdietrich** [comment]
done

**Comment by ewillink** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=579108 identifies that org.eclipse.xtext.generator is no longer fetchable although it is still packaged in the repo.

Workaround - augment all the *.target files from
    <unit id="org.eclipse.xtext.sdk.feature.group" version="0.0.0"/>
to
    <unit id="org.eclipse.xtext.generator.feature.group" version="0.0.0"/>
    <unit id="org.eclipse.xtext.sdk.feature.group" version="0.0.0"/>

Since Xtext has not undergone a major version change, surely the old generator must remain available?

Surely you need to offer e.g. org.eclipse.xtext.newsdk.feature.group to avoid breaking your previous contracts?

**Comment by cdietrich** [comment]
It is available. Simply use new feature in target

**Comment by cdietrich** [comment]
Alternative talk to the foundation about the reload4j crap they are doing and will even do worse
