### ISSUE TITLE
Tycho 3.0.0 includes imported stuff to update sites

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2094]
Tycho 3.0.0 includes imported stuff to update sites
this leads to our xtext update containing unwanted stuff and maybe even our dummy mwe features which are broken for sure

https://github.com/eclipse-tycho/tycho/issues/1281
https://github.com/eclipse-tycho/tycho/issues/898

to me it is unclear with what we need to replace the imports in the feature.xmls with

https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_tycho300test/lastSuccessfulBuild/artifact/build/p2-repository/plugins/

**Comment by cdietrich** [comment]
e.g.

```
./releng/org.eclipse.xtext.sdk.feature/feature.xml:      <import plugin="org.eclipse.emf.ecore" version="2.20.0" match="greaterOrEqual"/>
./releng/org.eclipse.xtext.sdk.feature/feature.xml:      <import plugin="org.eclipse.emf.common" version="2.17.0" match="greaterOrEqual"/>
./releng/org.eclipse.xtext.sdk.feature/feature.xml:      <import plugin="org.eclipse.emf.ecore.source" version="2.20.0" match="greaterOrEqual"/>
./releng/org.eclipse.xtext.sdk.feature/feature.xml:      <import plugin="org.eclipse.emf.common.source" version="2.17.0" match="greaterOrEqual"/>
./releng/org.eclipse.xtext.sdk.feature/feature.xml:      <import feature="org.eclipse.emf.mwe2.language.sdk" version="2.13.0" match="greaterOrEqual"/>
```

**Comment by LorenzoBettini** [comment]
I'm pretty sure that the first four are not needed anyway since they are compile-dependencies (required bundles) of some Xtext bundle.

**Comment by cdietrich** [comment]
the problem is i have no idea how to test this at all. nobody know how people install and consume stuff and what might break if removed.

**Comment by LorenzoBettini** [comment]
If that's the SDK feature, you can be sure that the EMF stuff is already downloaded (of course, if it can be found in any update site configured) because some Xtend bundle already depends on it. Note that this certainty is because they are bundles.
Again, I'm talking about those first 4 bundles.

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/commit/22de21cc01d5e01404c5da4f0c2d7881ef9038ad

**Comment by LorenzoBettini** [comment]
well, EMF SDK might have been too much for those installing Xtext SDK, that's why it was made more minimal.
But if those bundles are already required by one of our bundles with proper version ranges (and that's the case of at least one of the Xtext bundles) those additional requirements are useless.

requirements in features are only for things required at runtime (it's a kind of simplification) and not compile time.
required sources might still be useful though (sorry, I noted that only now), because I don't think that sources of required bundles are taken automatically...

Of course, I'm not saying that the referred issue in Tycho is OK, on the very contrary ;)

**Comment by cdietrich** [comment]
problem was solved in tycho
