### ISSUE TITLE
Create M0 milestone

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2152]
with publish to maven central
and std location of update site
+ adapt ref projects to use it

**Comment by cdietrich** [comment]
@LorenzoBettini i assume we are ready to work on this

**Comment by LorenzoBettini** [comment]
@cdietrich Yes, I'd like to have a try in the next few days. I still have to clean-up a few things and then I'll try.

**Comment by LorenzoBettini** [comment]
@cdietrich I'm going to experiment with the M0 milestone release.

Concerning the composite update site, I'll first dry-run, but the Maven artifacts will be deployed and staged on Sonatype. Please, don't release the staged repository for the moment.

**Comment by cdietrich** [comment]
should we do the steps to give you sonatype access for xtext.
if yes i would open a ticket if you give me the username

**Comment by cdietrich** [comment]
created https://issues.sonatype.org/browse/OSSRH-90485

**Comment by LorenzoBettini** [comment]
mhh... there are problems deploying to OSSRH / Maven Central

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0:deploy (default-deploy) on project xtext-parent: Failed to deploy artifacts: Could not transfer artifact org.eclipse.xtext:xtext-parent:pom:2.31.0.M0 from/to ossrh (https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/): authentication failed for https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/org/eclipse/xtext/xtext-parent/2.31.0.M0/xtext-parent-2.31.0.M0.pom, status: 401 Unauthorized
```

The job is similar to the one for deploying snapshots, so if we can deploy snapshots why can't we deploy releases?

**Comment by cdietrich** [comment]
good question. in the sign and deploy job

seems to use stuff like

-Posspub.userMavenSettings=/home/jenkins/.m2/settings.xml \
-Posspub.mavenSecurityFile=/home/jenkins/.m2/settings-security.xml \

but i dont know what is used from gradle and what is not.

**Comment by cdietrich** [comment]
from https://ci.eclipse.org/xtext/job/releng/job/sign-and-deploy/1926/consoleFull

```
03:53:38  Maven Settings: including user file /home/jenkins/.m2/settings.xml
03:53:38  Maven Settings: including security file /home/jenkins/.m2/settings-security.xml
03:53:38  Maven Settings: found 4 server entries
03:53:38  Maven Settings: using encrypted server entry for ossrh repository
```

**Comment by cdietrich** [comment]
indeed we pick the one with id == name
https://github.com/xtext/publishing/blob/aa97f2b592e9b64debde904ce262c35514a296a2/buildSrc/src/main/java/io/typefox/publishing/MavenPublishing.xtend#L313

**Comment by LorenzoBettini** [comment]
@cdietrich That was it! :)
Thanks!
The thing is not documented in Eclipse wiki

**Comment by LorenzoBettini** [comment]
@cdietrich would it be OK if I change a bit the directory structure for "drops" and milestones composite update site?

Instead of something like

`https://download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.30.0/S202301090721` (for milestone zips)
and
`https://download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.30.0/R202302271344` (for release zips)

something like

`https://download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.31.0/2.31.0.M1` (for milestone zips)
and
`https://download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.31.0/2.31.0` (for release zips)

For composite update site of milestones:

instead of

`https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/S202301090721/`

something like

`https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/2.31.0.M0`

For composite update site for releases it's already like that. For milestones is currently different.

This new schema:

- would make things clearer for browsing and for searching
- would make composite update site for milestones similar to the one of releases
- last, but not least, would save me a lot of work O:)

**Comment by cdietrich** [comment]
am reluctant, but dont know what the scripts that update the composite site etc do
@szarnekow what do you think?

**Comment by LorenzoBettini** [comment]
@cdietrich I'm not using the script for composite update site: I update the composite update site from the Maven build (it's configured in the POM).

**Comment by cdietrich** [comment]
ok then i propose to continue with that proposal for now

**Comment by LorenzoBettini** [comment]
Concerning the cleanup of old milestones, I guess you're referring to this part https://github.com/eclipse/xtext/blob/main/releng/jenkins/sign-and-deploy/Jenkinsfile#L63
that I can include in my Jenkinsfile for milestone release (upon M1).

This needs two adjustments:

- Instead of removing `/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S*` I can remove all the contents: `/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/*`. There's no need to keep the `composite*.xml` and `p2.index` since my Maven configuration seamlessly recreate them.
- Instead of removing **only** `/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/*/S*` I can remove **also** `/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/*/*.M*`, though the second regular expression is not needed yet for this version under development.

If there are problems updating the script for b3 aggregation I volunteer for updating b3 aggregation manually as I've always done for my other projects. However, that job is parameterized concerning the repository URL, so nothing should change I guess.

**Comment by LorenzoBettini** [comment]
@cdietrich I'd be ready to do the real M0 release. The dry-run of the update of the composite site looks good to me. I'd need to know whether I can simply add the M0 p2 repository as a child of the current milestone composite repository (which still includes the old milestones of 2.30) or if I should first wipe the current milestones composite repository.

Moreover, I can't see the staged repositories on https://s01.oss.sonatype.org/ I guess because I still don't have access rights. Could you please confirm that you see a few staged repositories for 2.31.0.M1 (I did a few experiments so there might be a few of them). If so, please remove them, so that the new staged repo will be the one to release.

**Comment by cdietrich** [comment]
i can see them there but the use seems to have changed.
should i try if they are closeable.
then i can do close and drop

**Comment by cdietrich** [comment]
closing xtend worked, xtext failed.
<div class="nx-staging-repository-ActivityView-messagePanel-head"><div class="nx-staging-repository-ActivityView-messagePanel-title">Event: Failed: POM Validation</div><div class="nx-staging-repository-ActivityView-messagePanel-timestamp">Wednesday, April 05, 2023 22:09:57 MS (GMT+0200)</div></div><div class="nx-staging-repository-ActivityView-messagePanel-body"><div class="nx-staging-repository-ActivityView-messagePanel-properties">

typeId | pom-staging
-- | --
failureMessage | Invalid  POM:  /org/eclipse/xtext/xtext-parent/2.31.0.M0/xtext-parent-2.31.0.M0.pom:  Project name missing, Project description missing

</div></div>

**Comment by cdietrich** [comment]
dropped both repos

**Comment by LorenzoBettini** [comment]
@cdietrich OK, then I can proceed with the real milestone release (I'll do that ASAP)

**Comment by LorenzoBettini** [comment]
@cdietrich can I proceed or should I wait for your currently pending PRs to be merged as well?

**Comment by cdietrich** [comment]
You should have access now. Of course you can proceed

**Comment by LorenzoBettini** [comment]
@cdietrich looks like JIRO has severe problems... :(

**Comment by cdietrich** [comment]
Is there already a ticket for it?

**Comment by LorenzoBettini** [comment]
@cdietrich looks like the situation has improved :)

**Comment by LorenzoBettini** [comment]
@cdietrich I made another experiment: the Maven staging repositories are there, the composite update site has NOT yet been created.

I can see the two staged repositories on Sonatype, I don't want to release them; I'm a bit rusted because I've always used the nexus stagine plugin.

Only the buttons "Close" and "Drop" are enabled. Is that expected?
Do you see the same situation?

I'd like to use the staging repositories in a Maven build locally, but I can't seem to find information about their URLs.

don't release them yet. I'll drop them once I've tested them and then do the real release also of the p2 composite update site.

**Comment by LorenzoBettini** [comment]
OK, maybe this page will help me: https://help.sonatype.com/repomanager2/staging-releases/managing-staging-repositories

I seem to understand that I first need to "Close" the repository so that I can test it.

**Comment by cdietrich** [comment]
Close
Means verify.

**Comment by cdietrich** [comment]
If successfully there will be release on closed entries

so first close both

**Comment by LorenzoBettini** [comment]
I tested everything locally (with the staged repository) and it seems to work great!

I'm about to do the real thing...

**Comment by LorenzoBettini** [comment]
@cdietrich @szarnekow it's done!

The 2.31.0.M0 repository

https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/2.31.0.M0/

is now part of the composite repository of milestones (the previous 2.30 milestones are still there, we can remove them at M1):

https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/

The zip is available from here:

https://download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.31.0.M0/

I intended that it would be available from drops/2.31.0/2.31.0.M0/ but in the end, the current form looks better to me.

Maven artifacts have been released.

Before releasing the staged artifacts I manually tested the milestone composite update site: it detected Xtext SDK 2.31. I installed Xtext SDK 2.31 in Eclipse, created a project, added the staged repositories in the parent POM, ran the Maven/Tycho build. Everything worked!

**Comment by cdietrich** [comment]
@LorenzoBettini  many thanks
TODO: 
- bootstrap xtext/main against M0 @LorenzoBettini  can you do that
- test bootstrap old gradle repos against m0 (i will do)
- consume m0 from ref projects (i will do)

**Comment by cdietrich** [comment]
@LorenzoBettini  did you already publish to maven central?

**Comment by LorenzoBettini** [comment]
@cdietrich I released the staging repository on Sonatype; synchronization with Maven Central should be automatic, shouldn't it? I takes some time though.

Bootstrapping against M0, just means changing the xtend-maven-plugin version or something else?

**Comment by cdietrich** [comment]
yes i mean the xtend maven plugin

**Comment by LorenzoBettini** [comment]
Bootstrapping (https://github.com/eclipse/xtext/pull/2205/commits/ceee86fb28447af0ffa96184d0f766e848e9e6d4) is part of the above PR

**Comment by cdietrich** [comment]
other bootstrap experiments look good. jenkins still behaves bad.

**Comment by cdietrich** [comment]
@LorenzoBettini should we build another M1 tomorrow or just contribute m0?

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini should we build another M1 tomorrow or just contribute m0?

I can't work on that today, neither tomorrow. We could contribute m0 in the meantime even just to check whether it aggregates with simrel.

**Comment by cdietrich** [comment]
yes i will give it a try

**Comment by cdietrich** [comment]
https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/201150

**Comment by LorenzoBettini** [comment]
I wonder why maven central still doesn't show the milestone version. It can be consumed in a maven build though. I thought synchronization was much faster.

**Comment by szarnekow** [comment]
![37BBFB94-7336-45AB-A2C2-0DDA05946704](https://user-images.githubusercontent.com/375492/230773299-6a8ecef0-27f9-41b4-874b-edc75fc5e204.jpeg)

looks good, doesn’t it?

**Comment by cdietrich** [comment]
@szarnekow how do you manage to get old ui for maven search ;)

**Comment by LorenzoBettini** [comment]
> ![37BBFB94-7336-45AB-A2C2-0DDA05946704](https://user-images.githubusercontent.com/375492/230773299-6a8ecef0-27f9-41b4-874b-edc75fc5e204.jpeg)
> 
> looks good, doesn’t it?

I still don't see the new versions..

**Comment by cdietrich** [comment]
i see it in legacy search but not in new
![Bildschirmfoto vom 2023-04-09 15-40-47](https://user-images.githubusercontent.com/238736/230776113-61ca1557-a778-410f-b24e-cb8ed658ce2b.png)
