### ISSUE TITLE
Deploy from monorepo

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2153]
deploy nightly from monorepo.
- disable old sign and deploy

**Comment by LorenzoBettini** [comment]
@cdietrich, which is the job that should be disabled?
I'd also like to see how that job is nightly triggered to update the new nightly job

**Comment by LorenzoBettini** [comment]
@cdietrich I consider this as fixed.

Now, also the zipped update file is uploaded here:
https://download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.31.0/

together with the computed md5 file

These contents https://download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.31.0/N202303281600/ have been uploaded by my job.

The corresponding Jenkinsfile https://github.com/eclipse/xtext/commit/cf2abd9baa7c1442c9e24ac5e4e8779f012e422d has been configured to run at nightly.

Could you please disable the old one?

I see there's a job that automatically keeps only 5 zip files; we should keep that job.

You'll note that my zip file is slightly bigger because I've just realized that we now publish in the p2 repo some test bundles. My bad! I merged the p2 repositories configurations from all the split repos and at that time you needed to temporarily publish also some test bundles. I've opened https://github.com/eclipse/xtext/issues/2159 to keep track of that.

You can close this issue after you disable the old nightly job, OK?

**Comment by cdietrich** [comment]
ok, we will see what the reference projects jobs will tell 2morrow

**Comment by LorenzoBettini** [comment]
@cdietrich 

This is the job: https://ci.eclipse.org/xtext/view/Xtext-release/job/xtext-monorepo-full-deploy-nightly/

the zipped repository in the download area has the same name schema as the previous ones, for example, tmf-xtext-Update-N202303281600.zip

the archived zip file in the job has the same name, see https://ci.eclipse.org/xtext/view/Xtext-release/job/xtext-monorepo-full-deploy-nightly/lastSuccessfulBuild/artifact/build/

**Comment by cdietrich** [comment]
so will try if i can workaround
using jenkins zip file downoad feature

**Comment by LorenzoBettini** [comment]
@cdietrich the zip can be found on the Jenkins archive or on the download area. That should be the same behavior as before.

**Comment by cdietrich** [comment]
@LorenzoBettini the problem is the name
we downloaded

https://ci.eclipse.org/xtext/job/xtext-umbrella/job/master/lastSuccessfulBuild/artifact/build/org.eclipse.xtext.sdk.p2-repository-2.31.0-SNAPSHOT.zip

in the past.
please note there is not date or timestamp in that name

**Comment by cdietrich** [comment]
20:09:18  Old version classes: 9120
20:09:18  New version classes: 16028
seems the testing stuff is also visible here
which also explains the memory problem

**Comment by LorenzoBettini** [comment]
@cdietrich 

Concerning the zip name, I can archive the zip repository in the job with the version and snapshot without the timestamp (I'll do that tomorrow).

The test bundles should be gone from the p2 repository once this https://github.com/eclipse/xtext/pull/2161 is merged (and the nightly site is rebuilt). In case you merge it yourself you'll have to rerun the nightly job. Otherwise, I'll do that tomorrow as well.

**Comment by cdietrich** [comment]
please do tomorrow. will then adapt the script again

**Comment by LorenzoBettini** [comment]
@cdietrich for the API diff, do you want to download the zip file from the nightly job (https://ci.eclipse.org/xtext/job/xtext-monorepo-full-deploy-nightly/lastSuccessfulBuild/artifact/build/) or the latest stable job of the main branch (https://ci.eclipse.org/xtext/job/xtext/job/main/lastSuccessfulBuild/artifact/build/)?

The zipped repository will have the name

```
org.eclipse.xtext.p2repository-2.31.0-SNAPSHOT.zip
```

OK? Note the project name is different from the old umbrella project.

**Comment by cdietrich** [comment]
will download it the from main.
will also update the file name

**Comment by LorenzoBettini** [comment]
@cdietrich this https://github.com/eclipse/xtext/commit/c487c75b9b47569ad3d4bbd62e59c57b639b6621 should implement it. As soon as the corresponding Jenkins job finished the build the API should work

**Comment by cdietrich** [comment]
Yes
