### ISSUE TITLE
Tycho 3 and Java toolchain

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2216]
If we switch to Tycho 3 we must use Java 17.

If we want to use Java 11 for building and testing there are basically two options:

- configure Jenkins so that, when running on Java 11, the `tycho-version` property is overridden on the command line
- use Maven toolchain as suggested in https://github.com/eclipse/xtext/pull/2210#issuecomment-1505885015

**Comment by cdietrich** [comment]
my main question about toolchains is:
- how can they easily be setup (maybe we need a template to adjust)
- how can i tell: run now with j11, run now with j17 ....

**Comment by LorenzoBettini** [comment]
@HannesWell but the Maven documentation mentions that you need to use a maven toolchain plugin, and I haven't found that in the SWT repository.

Please, remember that in some projects (packaging jar) the tycho-compiler-plugin is not used and the default maven-compiler-plugin is used.

**Comment by HannesWell** [comment]
> @HannesWell but the Maven documentation mentions that you need to use a maven toolchain plugin, and I haven't found that in the SWT repository.

That's probably because in the SWT repo there are not jar-typed projects.

> 
> Please, remember that in some projects (packaging jar) the tycho-compiler-plugin is not used and the default maven-compiler-plugin is used.

Then for xtext we probably need to configure both, tycho-compiler-plugin:useJDK and the maven-toolchain-plugin. I have not yet used the latter myself so cannot yet provide any more details in that regard yet.

In general it is often a good idea to only require toolchains in the CI activated in a corresponding Maven profile. This allows local builds without the need to set up toolchains on a computer. Then just the release option of the compiler is used, which is often not that bad. Using toolchains you can just be more confident.

@LorenzoBettini do you plan to provide a PR to do the migration to Tycho 3? Alternativly I can offer to work that out?

**Comment by LorenzoBettini** [comment]
@HannesWell I cannot work on that right now. If you are willing to work on that I can follow.

Of course, first, you can only try on GitHub Actions, then we'll deal with Jenkins.

First, let's hear from @cdietrich : do you think we can give it a try?

**Comment by cdietrich** [comment]
sure. give it a try.

**Comment by HannesWell** [comment]
> sure. give it a try.

Great, I have started to work on it. I'll provide a draft as soon.
If https://github.com/eclipse/xtext/pull/2214 is merged before that would avoid some unrelated changes. :)

**Comment by LorenzoBettini** [comment]
@HannesWell #2214 has been merged

**Comment by HannesWell** [comment]
Created https://github.com/eclipse/xtext/pull/2223 with the current state of the work, which should be quite complete besides the failures that have to be fixed.
