### ISSUE TITLE
Absolute paths in ._trace files when building with maven and xtext-maven-plugin

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2957]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=503309

**Comment by szarnekow** [comment]
Here we install a project config on the resource set
https://github.com/eclipse/xtext/blob/main/org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java#L412

That project config has enough information to provide source folders and the like - which allows to create a project relative path to the source file.

In the maven plugin, we should probably configure a proper project configuration provider that exposes the source folders etc to the languages, too.

https://github.com/eclipse/xtext/blob/main/org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/AbstractXtextGeneratorMojo.java#L187

**Comment by LorenzoBettini** [comment]
further hint: see what the `org.eclipse.xtext.xbase.testing.CompilationTestHelper.resourceSet(Pair<String, ? extends CharSequence>...)` does:

```java
	public ResourceSet resourceSet(@SuppressWarnings("unchecked") Pair<String,? extends CharSequence> ...resources ) throws IOException {
		XtextResourceSet result = newResourceSetWithUTF8Encoding();
		FileProjectConfig projectConfig = new FileProjectConfig(new File(workspaceRoot,PROJECT_NAME), PROJECT_NAME);
		projectConfig.addSourceFolder("src");
		ProjectConfigAdapter.install(result, projectConfig);
		for (Pair<String, ? extends CharSequence> entry : resources) {
			URI uri = copyToWorkspace(getSourceFolderPath()+"/"+entry.getKey(), entry.getValue());
			Resource resource = result.createResource(uri);
			if (resource == null)
				throw new IllegalStateException("Couldn't create resource for URI "+uri+". Resource.Factory not registered?");
			resource.load(result.getLoadOptions());
		}
		return result;
	}
```

**Comment by LorenzoBettini** [comment]
@szarnekow Do you think this could be done/addressed directly in the `StandaloneBuilder` when we pass the sources?

**Comment by ArneDeutsch** [comment]
Hi @LorenzoBettini. For a customer right now I look into this [issue](https://www.eclipse.org/forums/index.php/m/1853667/#msg_1853667). It seems it should be fixed with the commit https://github.com/eclipse/xtext/pull/3044 that has resolved this ticket. But updating to Xtext 2.35.0 does not resolve the issue for my project. It seems that one final step is missing to resolve this for all customers without additional changes.

Here (https://github.com/eclipse/xtext/pull/3044/commits/e597612a4c4ea091e531f2ac88e7de8eeb5670f1) you have a [FileProjectConfig](https://github.com/eclipse/xtext/blob/e8e6e6ddf933f7e6b10807328785cca7aeb26311/org.eclipse.xtext/src/org/eclipse/xtext/workspace/FileProjectConfig.java) registered, which seems correct. But the [DefaultTraceURIConverter](https://github.com/eclipse/xtext/blob/e8e6e6ddf933f7e6b10807328785cca7aeb26311/org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/DefaultTraceURIConverter.java) is using a [IProjectConfigProvider](https://github.com/eclipse/xtext/blob/e8e6e6ddf933f7e6b10807328785cca7aeb26311/org.eclipse.xtext/src/org/eclipse/xtext/workspace/IProjectConfigProvider.java). For a new DSL there is no implementation bound for this interface.

I can resolve the issue for my project by binding [ProjctConfigProvider](https://github.com/eclipse/xtext/blob/e8e6e6ddf933f7e6b10807328785cca7aeb26311/org.eclipse.xtext/src/org/eclipse/xtext/workspace/ProjectConfigProvider.java) in the RuntimeModule. I just wonder if we should bind this implementation by default. Or has this been deliberately NOT be done? To prevent changing things for existing projects? Or is it something that we should consider doing?

**Comment by LorenzoBettini** [comment]
Trace files work by default in xbase languages and the project config is enabled as well in xbase languages. Cc @szarnekow
