### ISSUE TITLE
Cannot build Xtext project with Java 11 due to transitive org.eclipse.core.runtime dependency

### ISSUE THREAD

**Issue by 6b6279** [eclipse/xtext#2988]
Hello,

recently, one of my Xtext projects stopped compiling, to be more succinct, it seems to fail the generateXtext target with the following error:
```
> com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
I am using Gradle 6.7 and Xtext 2.25, which both do not support Java 17, so it is crucial for me to stay on Java 11. It seems like the newest version of the org.eclipse.core.runtime artifact (3.31.0, which was released on March 11) was compiled with Java 17, which causes the breakage. Xtext doesn't explicitly depend on org.eclipse.core.runtime, so adding an upper bound for the dependency version isn't possible.

**Comment by cdietrich** [comment]
how do you create the project?

**Comment by 6b6279** [comment]
I do have the xtext-dev-bom set with ${xtextVersion} in my parent project. I tried `force "org.eclipse.platform:org.eclipse.core.runtime:3.30.0"` in the `build.gradle.kts` file of the failing submodule but it didn't have any effect. I have put that `force` entry in a `configurations.all` block, and in a `subprojects` block, moved it to the root project, nothing changed. Gradle keeps fetching 3.31.0...

**Comment by cdietrich** [comment]
can you provide a reproducer

**Comment by LorenzoBettini** [comment]
@6b6279 I know nothing about Gradle, but I have experience in Maven.

Has the problem started all of a sudden today? Have you updated any of your dependencies?

If you have this dependency chain, for example, 

A -> B -> org.eclipse.core.runtime

Where A and B also come from Eclipse platform, jdt or emf, which in the past the dependencies were not fixed but had ranges (a terrible anti-pattern), at least in Maven, if you don't want unwanted versions of dependencies then:

- pinning org.eclipse.core.runtime is not enough
- pinning A is not enough as well
- you have to pin them all

In the Xtext BOM we tried to pin them consistently, but IIRC, I fixed in the past an unpinned dependency from EMF, which gave us trouble when that was updated. Note: it was a transitive one that we didn't catch.

If this happened now without updating anything from your side, you've been hit by version ranges in Eclipse artifacts (not Xtext's fault, I mean).

Here are my suggestions:

- update to Xtext 2.34 (which doesn't require Java 17) so that you might benefit from our fix in the BOM
- at least, try quickly with Xtext 2.34 BOM
- try to debug the dependency chain (not easy, I warn you ;) you might take inspiration from the newer version of Xtext BOM
- if you don't want to update to new versions (which you better do, avoiding waiting too much), just commit the generated files and don't run the mwe2 generation

**Comment by 6b6279** [comment]
I'll try updating to Xtext 2.34, thanks a lot for your descriptive answer.

**Comment by cdietrich** [comment]
I don’t get the point . The bom is about the dependencies of xtext and not xtext itself. So you have to update both

**Comment by LorenzoBettini** [comment]
My suggestion was to quickly check whether updating the BOM would fix the mwe2 run.

**Comment by 6b6279** [comment]
Only updating the BOM fixes the generateXtext target, too. I have decided to just migrate my project(s) to Xtext 2.34, though. Thanks for your help.

**Comment by LorenzoBettini** [comment]
@6b6279 thank you for the feedback!

**Comment by 6b6279** [comment]
I have one more question: Is there a list somewhere with breaking changes for each Xtext release? I took a look at the changelogs but there wasn't a section along the lines of a "breaking changes" list.

**Comment by cdietrich** [comment]
what do you mean by breaking change. we usually try to avoid them.
the release notes will contain hints.

e.g. https://eclipse.dev/Xtext/releasenotes.html#/releasenotes/2023/11/21/version-2-33-0 
has removal hints

**Comment by 6b6279** [comment]
I was already using the BOM for version 2.25 when the initial issue with the org.eclipse.core.runtime dependency occurred. So I think using the recent BOM was definitely important.

I have asked the question because I have had to replace few instances of XtextResource with Resource, and now I am getting a NPE due to a missing EObject that is supposed to be imported from another file/namespace... which did not occur before the dependency issue broke my project and I had to upgrade to 2.34. I think'll just create a thread on the forums if I can't get it fixed after some nominal troubleshooting.
