### ISSUE TITLE
Check usage of quoted strings instead of multiline strings in some Xtend tests

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2999]
See https://github.com/eclipse/xtext/pull/2993#discussion_r1565708584

**Comment by HannesWell** [comment]
On a Windows computer you get the full list easily by running a full clean build and check the Git-Staging view for changed files, which gives me:
- `org.eclipse.xtend.core.tests.compiler.CompilerXtendIssue230Test`
- `org.eclipse.xtend.core.tests.macro.AbstractReusableActiveAnnotationTests`
- `org.eclipse.xtend.core.tests.smoke.SmokeTestCase`
- `org.eclipse.xtend.ide.tests.contentassist.Bug365368Test`
- `org.eclipse.xtend.ide.tests.contentassist.Issue624Test`
- `org.eclipse.xtend.ide.tests.editor.ImportAwareActionTest`
- `org.eclipse.xtend.ide.tests.macros.AbstractReusableActiveAnnotationTests`

But looking at the affected test cases, I don't think the usage of quoted string was on purpose and not by accident, because the strings using standard java quotes contain metacharacters for Xtend multi line strings like for example 
```
initializer = '''new «type.type»()'''
```
I can escape `'''` using `\'\'\'`, but for `« »` prepending them with back-slashes seems not to have the desired effect.

**Comment by LorenzoBettini** [comment]
Thanks for the analysis @HannesWell!

@szarnekow do you think we can turn those tests into multiline strings?

**Comment by HannesWell** [comment]
Your welcome.

I think I found a solution based on this answer: https://groups.google.com/g/xtend-lang/c/bVZ0nKmQGAI
Just put the sequence containing meta-character in a tag as string literal, i.e. wrap it with `«" "»`.

If you are fine with this, I can create a PR this evening.

**Comment by LorenzoBettini** [comment]
But that doesn't escape `«»` does it?

However, let's postpone this for the moment.

**Comment by HannesWell** [comment]
> But that doesn't escape `«»` does it?

It does if If wrap it into a tag with a literal string, like `«"«»"»` 

But this becomes a bit cumbersome if there are multiple such elements in a template.

So I'm not sure if it would be 'better' to migrate them directly to Java Text-Blocks.

**Comment by LorenzoBettini** [comment]
I think this can be closed now that https://github.com/eclipse/xtext/pull/3004 has been merged
