### ISSUE TITLE
Investigate if we can move xtext and mwe to  apache.commons.commons-logging 1.3.3

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3127]
starter for mwe https://github.com/eclipse/mwe/tree/cd-commons-logging

for xtext
- targets + build properties (also in wizard)
- maybe some remainder require bundles that are not import package yet
- ....

see also https://github.com/eclipse-simrel/simrel.build/pull/482

**Comment by HannesWell** [comment]
For MWE it looks doable to me to migrate off commons.logging (plus log4j) and just use for example slf4j:
- https://github.com/eclipse/mwe/pull/296

I have not yet checked if something similar can be done for xtext too, but maybe it's also possible.

In general instead of slf4j log4j-2 could be used as well. I have no strong preference and I guess for the usage in MWE/Xtext both have the same capabilities and both APIs cna be redirected if necessary.
