### ISSUE TITLE
Pot. Guava update needed

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3161]
https://github.com/eclipse-orbit/orbit-simrel/issues/41

@szarnekow @LorenzoBettini do you have any capacity. I don’t really have

(Also affects mwe)

**Comment by merks** [comment]
What needs to be done?

**Comment by merks** [comment]
Looking at SimRel right now, we already have duplicates because Papyrus has yet to provide an update for this release cycle and it's apparently futile to tell folks to stop including 3rd party bundles in their SimRel features:

![image](https://github.com/user-attachments/assets/4706bf52-df33-4edb-ab67-39ebd4718d72)

In any case, the new 33.3.0.jre version of guava fits into your current version range.

What problem are you anticipating?

**Comment by cdietrich** [comment]
Bump in poms targets new project wizard tests for wizard
Build another mwe milestone consume that in Xtext

create bump in Xtext/xtext-reference-projects to test

**Comment by cdietrich** [comment]
The version in target files is not a range

**Comment by cdietrich** [comment]
Also the Pom and Osgiversion should match

**Comment by szarnekow** [comment]
I think I can look into it this weekend

**Comment by cdietrich** [comment]
building mwe milestone m4 ....

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/pull/3163
might take some time to get green ....
when stuff is promoted to maven central

**Comment by szarnekow** [comment]
Thank you, @cdietrich
