### ISSUE TITLE
Introduce a bundle with dependencies for running MWE2 workflow

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3208]
Currently, our wizard generates a MANIFEST for the DSL project with `additional.bundles` like this:

```
additional.bundles = org.eclipse.xtext.xbase,\
                     org.eclipse.xtext.common.types,\
                     org.eclipse.xtext.xtext.generator,\
                     org.eclipse.emf.codegen.ecore,\
                     org.eclipse.emf.mwe.utils,\
                     org.eclipse.emf.mwe2.launch,\
                     org.eclipse.emf.mwe2.lib,\
                     org.objectweb.asm,\
                     org.apache.commons.commons-logging,\
                     org.apache.log4j
```

which are needed only for running the MWE2 workflow; in fact, we use `additional.bundles` instead of required bundles: they are not needed at run-time.

Keeping this list up-to-date becomes a burden for the users if we (Xtext) need to update them, as it happened with `commons-logging`: the user cannot benefit from any automatic update. The users must be notified and manually update the list.

Moreover, the plain Maven project our wizard generates add such dependencies as real dependencies of the DSL project, while it would be enough to have them in the `exec-maven-plugin` configuration.

Why don't we introduce a bundle, say `org.eclipse.xtext.generator.dependencies` that requires all of the above bundles and simply generate something like

```
additional.bundles = org.eclipse.xtext.generator.dependencies
```

This would allow us to keep the dependencies properly updated and the users won't have to do anything special when updating to a new version of Xtext. Similarly, we could simply add that dependency in the `exec-maven-plugin` configuration of a plain Maven project. (NOTE: `xtext-antlr-generator` should still be added in the POM because we cannot rely that to be present in an Eclipse TP).

By the way, having such bundle as part of Xtext SDK would have also saved us from explicitly add `commons-lang` in the SDK feature as done in https://github.com/eclipse/xtext/pull/3203. What's in there would be forced to be installed and issues like https://github.com/eclipse/xtext/issues/3192 wouldn't have happened.

Unless I miss something, maintaining such a bundle with proper dependencies cannot be harder than maintaining such a list in the wizard. For the users, the new bundle would be very helpful.

wdt @cdietrich @szarnekow

**Comment by szarnekow** [comment]
Very good idea. I'm all in favor of this.

**Comment by cdietrich** [comment]
hmmmm wasnt this aboished somewhen in the past or was this as xpand/xtend1 feature only?
i am still hoping eclipse will one day also support

addtionalImportedPackages ;)

**Comment by LorenzoBettini** [comment]
I don't remember it was abolished in the past.

**Comment by HannesWell** [comment]
> Why don't we introduce a bundle, say `org.eclipse.xtext.generator.dependencies` that requires all of the above bundles and simply generate something like

That's already a huge simplification, thanks for that!
In general I would strongly discourage from re-exporting dependencies, but in this case it is helpful and I think and hope the drawbacks don't apply since this bundle is not used at runtime, is it?

But wouldn't an ideal solution be that the MWE2 launches collect the required bundles/artifacts automatically without the need to specify them anywhere, just based on the metadata? At the moment the launch-type is just based on a simple Java launch that includes all jars on the project-classpath into the runtime, which is why these dependencies have to be added.
In PDE we do something similar, when automatically adding requirements of a Eclipse product/app launch. So this is possible.
The main question is 'just' what are the roots respectively drivers of the requirements? Are they defined in mwe or xtext or both?

If the requirements/dependency closure would be computed automatically, then nothing would have to be added and maintained anywhere and the number of jars in the mwe2 runtime would always be minimal.
I thought about this for a while already but I don't remember if I have written it down anywhere already. But if you are interested in such a change (probably in mwe), I would be happy to implement it.

**Comment by LorenzoBettini** [comment]
@HannesWell I wouldn't mind the idea, but I think it is intended to have control on the dependencies used when running the MWE2 launch, is that correct @cdietrich @szarnekow ?
